apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: shama123456/devopsk8s:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"  # Minimum memory that will be allocated
              cpu: "500m"      # Minimum CPU that will be allocated
            limits:
              memory: "512Mi"  # Maximum memory the container can use
              cpu: "1"         # Maximum CPU the container can use

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapp
