Update deploymentservice.yaml
e69cc6d
 · 
16 hours ago
History
Breadcrumbssimple-java-maven-app
/deploymentservice.yaml
File metadata and controls

Code

Blame
32 lines (32 loc) · 539 Bytes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: shama123456/devops-integration:latest
        ports:
        - containerPort: 8080
'''
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
